# This is a basic workflow to help you get started with Actions
# 개발 시에 쓰는 action

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Github Repository Secrets를 통해 환경 변수 파일을 생성합니다.
      - name: Generate Environment Variables File for Production
        run: |
          echo "VITE_SENDBIRD_API_KEY=$VITE_SENDBIRD_API_KEY" >> .env.production
          echo "VITE_BASE_URL=$VITE_BASE_URL" >> .env.production
          echo "VITE_GOOGLE_ANALYTICS_ID=$VITE_GOOGLE_ANALYTICS_ID" >> .env.production
        env:
          VITE_SENDBIRD_API_KEY: ${{ secrets.VITE_SENDBIRD_API_KEY }}
          VITE_BASE_URL: ${{ secrets.VITE_DEV_BASE_URL }}
          VITE_GOOGLE_ANALYTICS_ID: ${{ secrets.VITE_DEV_GOOGLE_ANALYTICS_ID }}
      
      - name: install packages
        run: npm install

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name : Check Node version
        run: node -v
        
      - name : project build
        run: npm run build
        
      # Deploy
      - name: Deploy
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: upload to s3 dev bucket                 # Upload build file to S3
        run: aws s3 sync ./dist s3://bandwagon-front-dev

      - name: Run a multi-line script
        run: |
          echo cf cache invalidation added
          echo Add other actions to build,
          echo test, and deploy your project.
